In [1]:
import tensorflow as tf

In [2]:
con_ten = tf.constant([[1,2],[3,4]])
print('Constant Tensor :\n',con_ten)

Constant Tensor :
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
var_ten = tf.Variable([[1,2],[3,4]])
print('Variable Tensor :\n',var_ten)

Variable Tensor :
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


In [5]:
row_con = tf.concat(values=[con_ten , var_ten], axis = 0)
print('Row Concatenate :\n',row_con)

Row Concatenate :
 tf.Tensor(
[[1 2]
 [3 4]
 [1 2]
 [3 4]], shape=(4, 2), dtype=int32)


In [6]:
col_con = tf.concat(values=[con_ten , var_ten], axis = 1)
print('Col Concatenate :\n',col_con)

Col Concatenate :
 tf.Tensor(
[[1 2 1 2]
 [3 4 3 4]], shape=(2, 4), dtype=int32)


In [8]:
zeros = tf.zeros(shape=[3,4,4],dtype=tf.int32)
print("Zero's Tensor : \n",zeros)

Zero's Tensor : 
 tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(3, 4, 4), dtype=int32)


In [9]:
ones = tf.ones(shape=[3,4,4],dtype=tf.int32)
print("One's Tensor : \n",ones)

One's Tensor : 
 tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(3, 4, 4), dtype=int32)
