IMPORTING LIBRARY

In [1]:
import tensorflow as tf

VERSION CHECK

In [ ]:
print('Tensorflow Version is ', tf.__version__)

Tensorflow Version is  2.15.0


EAGER EXECUTION

In [ ]:
if(tf.executing_eagerly()):
  print('Eager Execution Enabled')
else:
  print('Eager Execution not available. Upgrage Tensorflow 2.0.0+ ')


Eager Execution Enabled


GPU CHECK

In [ ]:
if(tf.test.gpu_device_name()):
  print('Default GPU Device Details:{}'.format(tf.test.gpu_device_name()))
else:
  print('Please install GPU based required resourses  and Tensorflow')

Please install GPU based required resourses  and Tensorflow


In [ ]:
con1=tf.constant([[1.4,2.1] ,[3,4.7]])
con2=tf.constant([[5],[2]])
con3=tf.constant([[5,4],[2,1]])

In [ ]:
print('Tensor con1:' , con1)
print(con2)
print(con3)

Tensor con1: tf.Tensor(
[[1.4 2.1]
 [3.  4.7]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5]
 [2]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[5 4]
 [2 1]], shape=(2, 2), dtype=int32)


In [ ]:
con1=tf.constant([[1.4,2.1,6] ,[3,4.7,5],[4,6,7]])
con2=tf.constant([[5,4,6],[2,7,8],[4,6,2]])
con3=tf.constant([[5,4,6],[2,1,5],[4,8,6]])

In [ ]:
print('Tensor con1:' , con1)
print(con2)
print(con3)

Tensor con1: tf.Tensor(
[[1.4 2.1 6. ]
 [3.  4.7 5. ]
 [4.  6.  7. ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[5 4 6]
 [2 7 8]
 [4 6 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[5 4 6]
 [2 1 5]
 [4 8 6]], shape=(3, 3), dtype=int32)


TRANSPOSE

In [ ]:
trans = tf.transpose(con2)
print('con2 Transpose :', trans)

con2 Transpose : tf.Tensor(
[[5 2 4]
 [4 7 6]
 [6 8 2]], shape=(3, 3), dtype=int32)


DATATYPE CHANGE

In [ ]:
con4 = tf.cast(con1,tf.float32)
con5 = tf.cast(con2,tf.float32)


In [ ]:
print('con4 Tensor:',con4)
print('con5 Tensor:',con5)

con4 Tensor: tf.Tensor(
[[1.4 2.1 6. ]
 [3.  4.7 5. ]
 [4.  6.  7. ]], shape=(3, 3), dtype=float32)
con5 Tensor: tf.Tensor(
[[5. 4. 6.]
 [2. 7. 8.]
 [4. 6. 2.]], shape=(3, 3), dtype=float32)


MULTIPLICATION ELEMENTS

In [ ]:
mul_elem = tf.multiply(con4,con5)
print('Element Multiplication :' , mul_elem)

Element Multiplication : tf.Tensor(
[[ 7.        8.4      36.      ]
 [ 6.       32.899998 40.      ]
 [16.       36.       14.      ]], shape=(3, 3), dtype=float32)


In [ ]:
con6=tf.constant([[1.4,2.1] ,[3,4.7]])
con7=tf.constant([[4],[2]])

In [ ]:
print('Tensor con6:' , con6)
print(con7)

Tensor con6: tf.Tensor(
[[1.4 2.1]
 [3.  4.7]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4]
 [2]], shape=(2, 1), dtype=int32)


In [ ]:
mul_mat = tf.matmul(con6,con7)
print('Element Multiplication :' , mat_mul)

DETERMINANT

In [ ]:
determinant = tf.linalg.det(con1)
print('Determinant of con1 : ', determinant)

Determinant of con1 :  tf.Tensor(-2.8399973, shape=(), dtype=float32)


TENSOR RESHAPE

In [ ]:
reshape_con4 = tf.reshape(tensor = con4, shape=[4,2])
print('Reshaped con4 :', reshape_con4)

Identity Matrix

In [ ]:
identity = tf.eye(num_rows = 2, num_columns = 3 , dtype = tf.int32)

In [ ]:
print('Identity matrix:',identity)

Identity matrix: tf.Tensor(
[[1 0 0]
 [0 1 0]], shape=(2, 3), dtype=int32)
